#!/usr/bin/env bash
# script that configure an Nginx server so that
# /redirect_me is redirecting to another page.

./1-install_nginx_web_server
sudo sed -i '/location \/ {/a \
\        location \/redirect_me {\
\            return 301 https:\/\/example.com\/new_page;\
\        }' /etc/nginx/sites-available/default

service nginx start
