#!/usr/bin/env bash
# script that configure an Nginx server redirect_me

# run bash script from task 1
./1-install_nginx_web_server

# configure redirect_me
url="https://www.youtube.com/watch?v=QH2-TGUlwu4"
replace="location /redirect_me {\nreturn 301 $url;\n}"
dest="/etc/nginx/sites-available/default"

sudo sed -i "s/server_name_;/server_name_;\n$replace" $dest

# restart nginx
sudo service nginx restart
