#!/usr/bin/env bash
# script that configure an Nginx server redirect_me

# run bash script from task 1
./1-install_nginx_web_server

# 404 error display
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

# create the error file
sudo mkdir /etc/nginx/html/

# configure the server
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;      
    }
}" | sudo tee /etc/nginx/sites-available/default

# restart nginx
sudo service nginx restart
