#!/usr/bin/env bash
# script that configure an Nginx server redirect_me

# update package list
sudo apt -y update

# Install Nginx
sudo apt install -y nginx

# Create a retrun string "Hello World!" when quering
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# 404 error display
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

# create the error file
sudo mkdir /etc/nginx/html/

# configure the server
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    server_name _;

    add_header X-Served-By $HOSTNAME;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;      
    }
}" | sudo tee /etc/nginx/sites-available/default

# restart nginx
sudo service nginx restart
