#!/usr/bin/env bash
# script that Install and configure HAproxy on your lb-01 server.

# install software properties not included in the default ubuntu
sudo apt install -y software-properties-common

# install HAproxy dependencies
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0

# update package list
sudo apt -y update

# Install Nginx
sudo apt install -y haproxy=2.0.\*

# configure the HAproxy
echo "
frontend http
	bind *:80
	default_backend servers

backend servers
	balance roundrobin
	server 302036-web-01 54.236.49.90:80 check
	server 302036-web-02 54.175.111.155:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# start HAproxy
sudo service start haproxy
