#!/usr/bin/env bash
# script that Install and configure HAproxy on your lb-01 server.

# install software properties not included in the default ubuntu
sudo apt install software-properties-common

# install HAproxy dependencies
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0

# update and install HAproxy
sudo apt update; sudo apt insatll -y haproxy

# configure the HAproxy
printf %s "

frontend http
	bind *:80
	default_backend servers

backend servers
	balance roundrobin
	server 302036-web-01 54.236.49.90:80 check
	server 302036-web-02 54.175.111.155:80 check

" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# start HAproxy
sudo service start haproxy
