#!/usr/bin/env bash
# this script:
#  Indefinitely writes I am alive! to the file /tmp/my_process
#  In between every I am alive! message, the program should
#+ pause for 2 seconds

while :
do
	echo "I am alive!" >> /tmp/my_process
	sleep 2
done
