#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hour=0

while ((hour <= 12))
do
	echo "Hour: $hour"

	min=1
	while ((min < 60))
	do
		echo "$min"
		((min++))
	done
	((hour++))
done
