#!/usr/bin/env bash
# This script displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

LIST=$(ls -1)
for i in $LIST
do
	echo "$i" | cut -f 2- -d '-'
done
