#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements.
#+ localhost resolves to 127.0.0.2 from 127.0.0.1
#+ facebook.com resolves to 8.8.8.8 from 157.240.11.35

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
sed -i s/157.240.11.35/8.8.8.8/ ~/hosts.new
cp -f ~/hosts.new /etc/hosts
